project:
  type: website

website:
  title: "351 Richland SF"
  google-analytics: "G-LDTXPT6F25"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: visit.qmd
        text: Visit
      - href: apply.qmd
        text: Application
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


